DELETE http://localhost:4000/api/tickets/ed7918b3-b421-43ce-968a-e5544095eeae HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTllY2JhNWFiZTBjYmQ2MmZjYzhhN2MiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzIwMTkzNzYsImV4cCI6MTc3MjAyMjk3Nn0.agq2A4WXBEzTzJFEB2s7ZMz4CG1M-k0iHTGSsxuoi00